name: CI

on:
  pull_request:
  push:
    branches: [develop, main]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install pre-commit
      - name: Lint
        run: task lint
      - name: Test
        run: task test
